#!/bin/bash

REDE_DOCKER="inbolso"

echo "----------------------------------"
echo "Preparando ambiente para deploy dos modulos"
echo "----------------------------------"

export PATH=$PATH:/usr/local/go/bin
export CGO_ENABLED=0
export GOOS=linux

echo "1 - Criando rede docker"
docker network create -d bridge ${REDE_DOCKER}

echo "2 - Dando permissões para arquivos executaveis"
chmod +x /sql/deploy
chmod +x /boletoapi/deploy
chmod +x /contabancariaapi/deploy
chmod +x /transferenciabancariaapi/deploy

echo "3 - REALIZANDO DEPLOY DA BASE DE DADOS"
./sql/deploy

echo "4 - REALIZANDO DEPLOY DO MODULO DE CONTA"
./contabancariaapi/deploy

echo "5 - REALIZANDO DEPLOY DO MODULO DE TRANSFERENCIA"
./transferenciabancariaapi/deploy

echo "6 - REALIZANDO DEPLOY DO MODULO DE BOLETO"
./boletoapi/deploy

echo "----------------------------------"
echo "Rotina de deploy finalizada"
echo "----------------------------------"